### ISSUE TITLE
http2Client.notifyError got notified that the client transport was broken EOF

### ISSUE THREAD

**Issue by GarimaSharma** [cloudfoundry-community/stackdriver-tools#107] opened 2017-09-04 16:05 UTC
Hi,

We are using Stackdriver nozzle tile 1.0.6 with PCF 1.11.6

We are not able to see logs in our Stackdriver/logging project. The error in Stackdriver-nozzle vm is:
`http2Client.notifyError got notified that the client transport was broken EOF`

We started seeing this issue exactly after installing 1.0.6 of Stackdriver nozzle. We upgraded directly from 1.0.3 to 1.0.6. 

Is there anyway to debug this?

**Comment by johnsonj** [comment] 2017-09-12 02:59
This specific error message comes from GRPC and is a somewhat generic error related to connections timing out. It in itself doesn't appear to be an indicator of failure. 

I updated to the latest GRPC/monitoring APIs in #113 which should quiet the error message based on grpc/grpc-go#1340.

The issue of not seeing logs is caused by #112 which is exacerbated by the new volume of logs being sent to Stackdriver with the addition of Metrics.

**Comment by johnsonj** [comment] 2017-10-11 21:14
Resolving. No work left on this issue.

**Closed by johnsonj** 2017-10-11 21:14 UTC
